*+--------------------------------------------------------------------
*+
*+ Source Module => c:\hmg.3.4.4\0\HBFM\\CREDBF.PRG
*+
*+    Copyright(C) 1983-2020 by Auge & Ohr
*+
*+    Functions: Procedure CreateNewDbf()
*+
*+    Reformatted by Click! 2.05.32 on Sep-10-2020 at  2:10 am
*+
*+--------------------------------------------------------------------

*+--------------------------------------------------------------------
*+
*+    Procedure CreateNewDbf()
*+
*+    Called from ( fmgrid.prg )   2 - procedure dualgrid()
*+                                   1 - static procedure dogridkey1()
*+                                   1 - static procedure dogridkey2()
*+
*+--------------------------------------------------------------------
*+
PROCEDURE CreateNewDbf()

*+ EOF: CREDBF.PRG
